Update Chokidar
I saw this error when running npm start:

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'

chokidar is some dependency of React that somehow got out of date. https://www.npmjs.com/package/chokidar

That error lead me to this page: https://stackoverflow.com/a/67739231 which had the solution of running:

Ran npm update chokidar